apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: dbpepper
  name: dbpepper
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: dbpepper
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: dbpepper
    spec:
      containers:
        - name: postgresdbpepper
          image: registry.cloud.htl-leonding.ac.at/l.federsel/pepperpostgresdb_pepper:latest
          env:
            - name: POSTGRES_DB
              value: postgres
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-password-secret
                  key: db-password
          ports:
            - containerPort: 5432
          resources: {}
          envFrom:
            - secretRef:
                name: db-password-secret
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: postgresdbpepper
  labels:
    app: dbpepper
    service: postgresdbpepper
spec:
  type: NodePort
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
  selector:
    io.kompose.service: dbpepper
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dbpepper
  namespace: student-l-federsel
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: standard
  resources:
    requests:
      storage: 50Mi
---
apiVersion: v1
kind: Secret
metadata:
  name: db-password-secret
type: Opaque
data:
  db-password: NGJya3VGM0JFcE9NMTNKYXMxd24=
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dbpepper-ingress
  namespace: student-l-federsel
spec:
  rules:
    - host: student.cloud.htl-leonding.ac.at
    - http:
        paths:
          - path: /dbpepper
            pathType: Prefix
            backend:
              service:
                name: postgresdbpepper
                port:
                  number: 5432
