version: '3'
services:
  db:
    image: registry.cloud.htl-leonding.ac.at/l.federsel/pepperpostgresdb_pepper:latest
    container_name: lawrence.federsel_postgresdb_pepper
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pepper_database
    expose:
     - "5432"
    ports:
      - "5433:5432"
  quarkus:
    image: registry.cloud.htl-leonding.ac.at/l.federsel/pepper_quarkus:latest
    container_name: l.federsel_pepper_quarkus
    depends_on:
        - db
    expose:
     - "8080"
    ports:
      - "8080:8080"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: standard
  resources:
    requests:
      storage: 50Mi´
